
-- File: 0016_create_volunteering_activities_table_community.up.sql
-- Description: Create the volunteering activities table

CREATE TABLE IF NOT EXISTS volunteering_activities
(
    id       UUID PRIMARY KEY DEFAULT public.uuid_generate_v4(),
    activity VARCHAR(255)
);

INSERT INTO volunteering_activities (activity)
VALUES ('Food Drive'),
       ('Community Clean-Up'),
       ('Mentorship Program'),
       ('Senior Companion'),
       ('Environmental Conservation'),
       ('Homeless Shelter Support'),
       ('Children''s Hospital Activities'),
       ('Tutoring and Education'),
       ('Animal Shelter Assistance'),
       ('Disaster Relief'),
       ('Soup Kitchen Help'),
       ('Blood Donation'),
       ('Library Volunteering'),
       ('Elderly Care Visits'),
       ('Crisis Hotline Support'),
       ('Park Restoration'),
       ('Youth Sports Coaching'),
       ('Community Garden Care'),
       ('Meals on Wheels'),
       ('Charity Run/Walk'),
       ('Veterans Support'),
       ('Beach Cleanup'),
       ('Literacy Programs'),
       ('Art Therapy'),
       ('Eco-Friendly Workshops'),
       ('Wildlife Rescue'),
       ('Habitat for Humanity'),
       ('Holiday Toy Drive'),
       ('Home Repair Assistance'),
       ('Special Olympics'),
       ('Farm Volunteer'),
       ('Environmental Education'),
       ('Music Therapy'),
       ('Community Center Help'),
       ('Refugee Aid'),
       ('Pet Adoption Events'),
       ('Fundraising Events'),
       ('Disability Support'),
       ('Soup Kitchen Serving'),
       ('Blood Drive Organizer'),
       ('School Supplies Drive'),
       ('Animal Foster Care'),
       ('Historical Preservation'),
       ('After-School Programs'),
       ('Hospital Volunteer'),
       ('Disaster Recovery'),
       ('Arts and Crafts Workshops'),
       ('Local Sports Coaching'),
       ('Cancer Support Groups'),
       ('Other');
